# Generated by Django 3.0.5 on 2020-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date_visited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
